### PR TITLE
Update all packages

### LINKED ISSUE #5: Compatibility with aframe master threejs r141
When you will try to update your project to use latest aframe master, here is the list of the changes needed in the different libraries so you don't need to search for all the PR I just did :)
`THREE.Math` was removed in threejs r141, it needs to be replaced with `THREE.MathUtils`

You need
- networked-aframe 0.10.0 that includes https://github.com/networked-aframe/networked-aframe/pull/343
- https://github.com/diarmidmackenzie/christmas-scene/pull/2
- https://github.com/n5ro/aframe-extras/pull/377

In the meantime, you can also use:
```
<script src="aframe-master.min.js"></script>
<script>
  THREE.Math = THREE.MathUtils;
</script>
```

### PR DESCRIPTION
**Pull request by vincentfretin**
This closes #5

### CODE REVIEW

**Comment by vincentfretin** [comment]
I tested VR on Quest and AR on Chrome Android on this glitch https://glitch.com/edit/#!/vfretin-aframe-xr-starterkit
no regression as far as I can tell, only bugfixes. :)

**Comment by vincentfretin** [comment]
Previously in VR with movement-controls right joystick didn't work to move the camera, now it works since https://github.com/n5ro/aframe-extras/pull/373 was merged but if I move position with left joystick afterwards it doesn't go in the correct direction. Funny I don't have this issue at all in my app and the code is the same as far as I can tell except my camera has id="camera" and yours id="head".
There is another thing that bother me, it moves forward now when I press trigger when movement-controls is enabled, I'm not sure what changes introduced that.

**Comment by vincentfretin** [comment]
I removed your hack that reset the cameraRig rotation to y=0 when switching to movement-controls.
My guess is that you added this hack because of the issue:
- https://github.com/n5ro/aframe-extras/issues/394

that I now fixed in the PR:
- https://github.com/n5ro/aframe-extras/pull/396

I used the build of this PR here.

**Comment by vincentfretin** [comment]
If I comment the main.js file, I don't have the issue anymore where the left joystick goes into the wrong direction, so there is something in main.js that does something on cameraRig or camera rotation.

**Comment by vincentfretin** [comment]
It's your xr-follow component that causes the issue, but I don't understand why. This component is set on the parent of the sword and watergun. I don't understand why it impacts cameraRig/camera heading when moving.

**Comment by AdaRoseCannon** [comment]
Oh that’s weird it shouldn’t change anything else. I’ll take a quick look.

**Comment by vincentfretin** [comment]
I found it. It's the following code:
```
const cameraObject = scene.camera;
const camera = scene.is('vr-mode') ? scene.renderer.xr.getCamera(cameraObject) : cameraObject;
```
`scene.renderer.xr.getCamera` is overriding the active camera `scene.camera` I think.

If I replace those line by just
```
const camera = scene.camera;
```
it seems to work properly. I see the sword and watergun, I can grab both.

**Comment by AdaRoseCannon** [comment]
That was to get it working in VR glad it is no longer needed but weird that it would have side effects

**Comment by vincentfretin** [comment]
Yes it's a bit weird, I don't fully understand it, but if the code is simpler, still work in VR and this fixes the movement issue, then I won't dig it further. :)

**Comment by vincentfretin** [comment]
Ok so there is only one issue remaining before we can merge. This is this issue:
- https://github.com/n5ro/aframe-extras/issues/392

**Comment by vincentfretin** [comment]
Yeah I really don't understand how the issues are related :D How it can impact the heading calculation here
https://github.com/n5ro/aframe-extras/blob/5b1339d86f59e871931a7e94f51288f59364aa6a/src/controls/movement-controls.js#L191-L194

I just wanted to mention getCamera has no argument in threejs r144
https://github.com/mrdoob/three.js/blob/68daccedef9c9c325cc5f4c929fcaf05229aa1b3/src/renderers/webxr/WebXRManager.js#L560-L564
so the previous code was slightly wrong, in this threejs version anyway.

**Comment by vincentfretin** [comment]
FYI in threejs r144 we have this change https://github.com/mrdoob/three.js/commit/777f97a0425c806f3ef7fb670a74e91373e23068
that's probably why we don't need the previous fix now.

**Comment by vincentfretin** [comment]
Alright, I fixed the issue https://github.com/n5ro/aframe-extras/issues/392 with trigger moving forward, that was a regression when I merged the changes in touch-controls for Chrome Android Cardboard button.
I currently use an aframe-extras build with https://github.com/n5ro/aframe-extras/pull/396 changes. Let's wait a few days if someone has any feedback on those changes. Once this is merged, you will be able to merge this PR too.

You can test the changes in my glitch https://glitch.com/edit/#!/vfretin-aframe-xr-starterkit

**Comment by AdaRoseCannon** [comment]
> FYI in threejs r144 we have this change [mrdoob/three.js@777f97a](https://github.com/mrdoob/three.js/commit/777f97a0425c806f3ef7fb670a74e91373e23068)
> that's probably why we don't need the previous fix now.

Nice find!

**Comment by AdaRoseCannon** [comment]
Thank you for all the fixes, glad to see so many hacks removed

**Comment by vincentfretin** [comment]
I merged the aframe-extras PR, now using again a build from aframe-extras master.
I updated to use an aframe master build with three r147 (r144 previously), there are no new warning or error. I tested in VR, grabbing the sword, climbed the ladder, and tested again AR mode on Chrome Android.
You can merge now or wait for aframe 1.4.0 in a week or two as you wish.

**Comment by AdaRoseCannon** [comment]
Fantastic! Let’s merge:D

Thank you so much for all of your work in this!

**Comment by vincentfretin** [comment]
Cool, thanks. Please don't forget to update the glitch as well. I'm not sure what it your workflow here, you just open the glitch terminal and `git pull` and `refresh` I guess?

**Comment by AdaRoseCannon** [comment]
Updated

**Pull request merged**
